# Generated by Django 4.0.3 on 2024-04-05 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_alter_farm_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='custom_percentage',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='farm',
            name='duration',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
    ]
