# Generated by Django 4.0.3 on 2024-04-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_farm_custom_percentage_alter_farm_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='duration',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
