# Generated by Django 4.0.3 on 2024-04-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_alter_farm_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
