# Generated by Django 4.0.3 on 2024-04-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croptype',
            name='crop_image',
            field=models.ImageField(blank=True, upload_to='croptype_images/'),
        ),
        migrations.AlterField(
            model_name='croptype',
            name='slug',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
